server:
  port: 8990

spring:

#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    order-service: /api/order/**
    product-service: /api/product/**
   #屏蔽默认的入口方式/order-service/api/v1/order/save
  ignored-patterns: /*-service/**

#设置超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000


ribbon:
  ReadTimeout: 3000
  ConnectTimeout: 3000
