#指定注册中心地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#服务的名称
spring:
  application:
    name: order-service
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 2000
    password: iflytek!1
  zipkin:
    base-url: http://192.168.137.210:9411/
      #配置采样百分比,开发环境可以设置为1，表示全部，生产就用默认
    sleuth:
       sampler:
         probability: 1



server:
  port: 8810


#修改调用超时时间
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 1000

#设置超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000

#暴露全部的监控信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
